---
title: "Results"
author: "Dimuthu Ratnadiwakara"
date: "2024-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())
library(data.table)
library(RSQLite)
library(DBI)
library(dplyr)
library(lfe)
library(stargazer)
library(ggplot2)
library(readxl)

source('https://raw.githubusercontent.com/dratnadiwakara/r-functions/main/functions.R')

raw_data_path <- 'D:/OneDrive/research-data/'
processed_data_path <- 'D:/OneDrive/project-data/cse-bank-risk/'
```



```{r}
hmda_link_entity <- fread(paste0(raw_data_path,"HMDA/HMDA lender/hmdapan2017.csv"),select=c("code","hmprid",paste0("RSSD",12:17)))#,paste0("ENTITY",15:16)
hmda_link_entity[,hmda_id:=paste0(code,"-",hmprid)]
hmda_link_entity[,c("code","hmprid"):=list(NULL)]
hmda_link_entity <- melt(hmda_link_entity,id.vars = c("hmda_id"))
hmda_link_entity <- data.table(hmda_link_entity)
hmda_link_entity <- hmda_link_entity[!is.na(value)]
hmda_link_entity[,year:=as.character(variable)]
hmda_link_entity[,year:=substr(year,5,6)]
setnames(hmda_link_entity,"value","RSSD")
hmda_link_entity[,variable:=NULL]
hmda_link_entity[,year:=as.numeric(year)]
hmda_link_entity[,year:=ifelse(year>85,1900+year,2000+year)]


hmda_link_2021 <- fread(paste0(raw_data_path,"/HMDA/HMDA lender/hmdapan2021.csv"),select=c("LEI","RSSD21","CODE21","HMPRID"))

hmda_link_2021[,hmda_id:=paste0(CODE21,"-",HMPRID)]
hmda_link_2021 <- hmda_link_2021[,c("LEI","RSSD21","hmda_id")]

saveRDS(hmda_link_2021,paste0(processed_data_path,"hmda_link_2021.rds"))
```



```{r}
gse_limit_files <- list.files(paste0(raw_data_path,"GSE Limits"),full.names = T,pattern = ".xls")
gse_limits <- list()
i=1
for(fl in gse_limit_files) {
  yr <- regmatches(fl, gregexpr("\\d{4}", fl))[[1]]
  temp <- read_xls(fl,sheet = 1,skip=2,col_names = F)  
  names(temp) <- c("statefips","countyfips","countyname","cbsa","statecode","gse_limit","gse_limit_2","gse_limit_3","gse_limit_4")
  temp <- data.table(temp)
  temp[,year:=yr]
  gse_limits[[i]] <- temp
  i=i+1
}

gse_limits <- rbindlist(gse_limits)
gse_limits[,gse_limit:=floor(gse_limit/1000)]
gse_limits[,year:=as.numeric(year)]



gse_limits[,county:=paste0(statefips,countyfips)]

gse_limits <- gse_limits[,c("county","year","gse_limit")]

setorder(gse_limits,county,year)
gse_limits[,gse_limit_1:=lag(gse_limit),by=county]
gse_limits[,gse_limit_2:=lead(gse_limit),by=county]

gse_limits[,limit_change:=gse_limit-gse_limit_1]

saveRDS(gse_limits,paste0(processed_data_path,"gse_limits.rds"))


```


```{r}
hmda_con <- dbConnect(RSQLite::SQLite(), paste0(raw_data_path,"HMDA/hmda.db"))

yrs <- as.character(2012:2017)
hmda <- list()
i=1
for(yr in yrs) {
  print(yr)
  hmda[[i]] <- data.table(dbGetQuery(hmda_con,
                                     paste0("select
                                                agencycode,
                                                respondentid,
                                                asofdate,
                                                purposeofloan,
                                                typeofpurchaser,
                                                amountofloan,
                                                censustract,
                                                applicantincome,
                                                typeofloan,
                                                actiontaken
                                            from lar 
                                            where 
                                            actiontaken in (1,3,6) and
                                            propertytype==1")))
  i=i+1
}
```



